In [2]:
import pandas as pd
df = pd.read_csv('student_performance.csv')
print('Student loaded successfully!')

Student loaded successfully!

In [3]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [5]:
print('Shape of dataset', df.shape)
print('Number of students:', df.shape[0])
print('Number of columns', df.shape[1])

Shape of dataset (30, 13)
Number of students: 30
Number of columns 13

In [7]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [9]:
print('columns in the dataset:')
print(df.columns.tolist())

columns in the dataset:
['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [10]:
df.columns.tolist()

['student_id',
 'name',
 'age',
 'gender',
 'department',
 'semester',
 'math_score',
 'science_score',
 'english_score',
 'programming_score',
 'attendance_percentage',
 'city',
 'admission_year']

In [11]:
print('data types')
print(df.dtypes)
df.describe()

data types
student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [13]:
print("missing values in each column")
print(df.isnull().sum())
print('\nInitial total missing values:', df.isnull().sum().sum())

missing values in each column
student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

Initial total missing values: 0

In [15]:
print('department in this dataset:')
print(df['department'].unique())

department in this dataset:
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [19]:
print('how many students per department ')
print(df['department'].value_counts())

how many students per department
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [23]:
cs_students=df[df['department']== 'Computer Science']
print(f'Number of Computer Science students: {len(cs_students)}')

Number of Computer Science students: 13

In [27]:

high_attendance = df[df['attendance_percentage'] > 90]


print(f'Students with attendance above 90%: {len(high_attendance)}')

print(high_attendance[['name', 'department', 'attendance_percentage']])

Students with attendance above 90%: 10
              name        department  attendance_percentage
0     Aarav Sharma  Computer Science                     92
3      Sneha Reddy        Mechanical                     95
7      Divya Singh  Computer Science                     96
9       Ananya Das  Computer Science                     98
13   Kavya Nambiar        Mechanical                     91
15    Ritu Agarwal       Electronics                     93
17  Swati Kulkarni  Computer Science                     94
21     Tanvi Mehta  Computer Science                     97
24       Amit Bose  Computer Science                     91
29  Akanksha Yadav  Computer Science                     95

In [8]:
import pandas as pd
df = pd.read_csv('student_performance.csv')
df['total_score'] = df['math_score'] + df['science_score'] + df['english_score'] + df['programming_score']
top_student = df.loc[df['total_score'].idxmax()]
print(top_student)

student_id                           1010
name                           Ananya Das
age                                    19
gender                             Female
department               Computer Science
semester                                2
math_score                             95
science_score                          89
english_score                          90
programming_score                      97
attendance_percentage                  98
city                              Kolkata
admission_year                       2023
total_score                           371
Name: 9, dtype: object

In [ ]:
df_sorted=df.sort_values(by)

In [10]:
dept_avg = df.groupby('department')['total_score'].mean().round(2)
print("Average total Score by Department:")
print(dept_avg)

Average total Score by Department:
department
Civil               235.80
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Name: total_score, dtype: float64

In [12]:
df_sorted=df.sort_values(by='total_score',ascending=False)
print("top 5 students based on total score")
print(df_sorted.head)

top 5 students based on total score
<bound method NDFrame.head of     student_id            name  age  gender        department  semester  \
9         1010      Ananya Das   19  Female  Computer Science         2
21        1022     Tanvi Mehta   19  Female  Computer Science         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2
4         1005      Arjun Nair   19    Male  Computer Science         2
7         1008     Divya Singh   19  Female  Computer Science         2
17        1018  Swati Kulkarni   19  Female  Computer Science         2
24        1025       Amit Bose   19    Male  Computer Science         2
12        1013      Suresh Rao   21    Male  Computer Science         2
19        1020    Nisha Kapoor   19  Female  Computer Science         2
0         1001    Aarav Sharma   19    Male  Computer Science         2
26        1027   Gaurav Shukla   21    Male  Computer Science         2
15        1016    Ritu Agarwal   20  Female       Electronics         2
1         1002     Priya Patel   20  Female  Computer Science         2
10        1011     Vikram Iyer   20    Male       Electronics         2
23        1024   Preeti Saxena   20  Female        Mechanical         2
25        1026      Rekha Nair   20  Female       Electronics         2
13        1014   Kavya Nambiar   20  Female        Mechanical         2
14        1015     Ajay Tiwari   19    Male  Computer Science         2
3         1004     Sneha Reddy   20  Female        Mechanical         2
28        1029      Nitin Jain   20    Male        Mechanical         2
11        1012     Pooja Gupta   19  Female             Civil         2
20        1021   Harish Pillai   20    Male       Electronics         2
2         1003     Rohit Verma   19    Male       Electronics         2
18        1019  Deepak Chauhan   20    Male        Mechanical         2
6         1007     Kiran Kumar   21    Male             Civil         2
5         1006     Meera Joshi   20  Female       Electronics         2
8         1009    Rahul Mishra   20    Male        Mechanical         2
27        1028   Sunita Pillai   19  Female             Civil         2
22        1023    Sanjay Dubey   21    Male             Civil         2
16        1017    Manoj Pandey   21    Male             Civil         2

    math_score  science_score  english_score  programming_score  \
9           95             89             90                 97
21          93             90             88                 96
29          91             93             87                 94
4           92             88             81                 95
7           88             91             84                 93
17          90             87             85                 92
24          86             82             79                 89
12          83             86             77                 88
19          79             84             81                 83
0           85             78             72                 91
26          84             79             75                 87
15          87             83             86                 69
1           76             82             88                 79
10          80             75             68                 72
23          77             81             76                 53
25          72             77             73                 63
13          74             78             82                 51
14          71             69             64                 76
3           70             80             75                 48
28          75             76             70                 50
11          67             72             79                 44
20          64             70             67                 58
2           65             74             61                 55
18          68             73             62                 49
6           73             69             65                 40
5           58             66             70                 52
8           62             71             58                 45
27          60             65             68                 39
22          61             66             59                 42
16          56             61             55                 38

    attendance_percentage                city  admission_year  total_score
9                      98             Kolkata            2023          371
21                     97               Surat            2023          367
29                     95                Agra            2023          365
4                      90               Kochi            2023          356
7                      96             Lucknow            2023          356
17                     94              Nagpur            2023          354
24                     91             Kolkata            2023          336
12                     88              Mysore            2023          334
19                     89          Chandigarh            2023          327
0                      92              Mumbai            2023          326
26                     87             Lucknow            2023          325
15                     93                Agra            2023          325
1                      87           Ahmedabad            2023          325
10                     83             Chennai            2023          295
23                     86              Kanpur            2023          287
25                     82               Kochi            2023          285
13                     91            Thrissur            2023          285
14                     75              Bhopal            2023          280
3                      95           Hyderabad            2023          273
28                     84              Indore            2023          271
11                     80              Jaipur            2023          262
20                     74  Thiruvananthapuram            2023          259
2                      78               Delhi            2023          255
18                     77            Dehradun            2023          252
6                      85           Bangalore            2023          247
5                      72                Pune            2023          246
8                      68            Varanasi            2023          236
27                     73  Thiruvananthapuram            2023          232
22                     70           Allahabad            2023          228
16                     65               Patna            2023          210  >