<a href="https://colab.research.google.com/github/jacquiline18/Jacquiline-CodeBooster-Internship-2026-Phase_01-Data_Engineering-/blob/main/Day_02_SQL_visualization_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
print('All lib imported succesfully')
print('pandas version:(pd__version__)')
print('sqlite3 version:(sqlite3.version)')

All lib imported succesfully
pandas version:(pd__version__)
sqlite3 version:(sqlite3.version)

In [3]:
from  google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
df=pd.read_csv('student_performance.csv')
print("Dataset loaded:{df.shape[0]} students,{df.shape[1]}columns")
print("First 3 rows")
df.head()

Dataset loaded:{df.shape[0]} students,{df.shape[1]}columns
First 3 rows

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [6]:
conn = sqlite3.connect(':memory:')
df.to_sql('students', conn, if_exists='replace', index=False)
cursor = conn.cursor()
cursor.execute('SELECT COUNT(*)FROM students')
count=cursor.fetchone()[0]
print(f"Number of students: {count}")
conn.close()

Number of students: 30

In [10]:
conn = sqlite3.connect(':memory:')
df.to_sql(
    name='students',
    con=conn,
    if_exists='replace',
    index=False
)
conn.close()

In [12]:
conn = sqlite3.connect(':memory:')
df.to_sql('students', conn, if_exists='replace', index=False)
cursor = conn.cursor()
cursor.execute("PRAGMA table_info(students)")
columns_info=cursor.fetchall()
print("Table structure of 'students':")
print(f"{'Column Name':<25} {'Data Type':<12}")
print("."*38)
for col in columns_info:
  print(f"{col[1]:<25} {col[2]:<12}")
conn.close()

Table structure of 'students':
Column Name               Data Type
......................................
student_id                INTEGER
name                      TEXT
age                       INTEGER
gender                    TEXT
department                TEXT
semester                  INTEGER
math_score                INTEGER
science_score             INTEGER
english_score             INTEGER
programming_score         INTEGER
attendance_percentage     INTEGER
city                      TEXT
admission_year            INTEGER

In [15]:
def run_query(sql, description=""):
  conn = sqlite3.connect(':memory:')
  df.to_sql('students', conn, if_exists='replace', index=False)
  if description:
    print(f"\n{'='*55}")
    print(f"{description.upper()}")
    print(f"{'='*55}")
  result=pd.read_sql_query(sql, conn)
  print(result)
  conn.close()
  return result

In [21]:
query1= """SELECT name, department, math_score
FROM
students ORDER
BY math_score DESC LIMIT 5"""

In [22]:
run_query(query1, description="Top 5 Students by Math Score")

=======================================================
TOP 5 STUDENTS BY MATH SCORE
=======================================================
             name        department  math_score
0      Ananya Das  Computer Science          95
1     Tanvi Mehta  Computer Science          93
2      Arjun Nair  Computer Science          92
3  Akanksha Yadav  Computer Science          91
4  Swati Kulkarni  Computer Science          90

             name        department  math_score
0      Ananya Das  Computer Science          95
1     Tanvi Mehta  Computer Science          93
2      Arjun Nair  Computer Science          92
3  Akanksha Yadav  Computer Science          91
4  Swati Kulkarni  Computer Science          90

In [23]:
query2= """SELECT name, department, attendance_percentage FROM students WHERE attendance_percentage > 90 ORDER BY attendance_percentage DESC"""

In [24]:
run_query(query2, description="Students with High Attendance (>90%)")

=======================================================
STUDENTS WITH HIGH ATTENDANCE (>90%)
=======================================================
             name        department  attendance_percentage
0      Ananya Das  Computer Science                     98
1     Tanvi Mehta  Computer Science                     97
2     Divya Singh  Computer Science                     96
3     Sneha Reddy        Mechanical                     95
4  Akanksha Yadav  Computer Science                     95
5  Swati Kulkarni  Computer Science                     94
6    Ritu Agarwal       Electronics                     93
7    Aarav Sharma  Computer Science                     92
8   Kavya Nambiar        Mechanical                     91
9       Amit Bose  Computer Science                     91

             name        department  attendance_percentage
0      Ananya Das  Computer Science                     98
1     Tanvi Mehta  Computer Science                     97
2     Divya Singh  Computer Science                     96
3     Sneha Reddy        Mechanical                     95
4  Akanksha Yadav  Computer Science                     95
5  Swati Kulkarni  Computer Science                     94
6    Ritu Agarwal       Electronics                     93
7    Aarav Sharma  Computer Science                     92
8   Kavya Nambiar        Mechanical                     91
9       Amit Bose  Computer Science                     91

In [26]:
query5 ="""
 SELECT
  department,
  COUNT(*) AS student_count,
  ROUND(AVG(math_score),2) AS avg_math_score,
  ROUND(AVG(science_score),2)AS avg_science,
  ROUND(AVG(programming_score),2) AS avg_programming
FROM STUDENTS
GROUP BY department
ORDER BY avg_math_score DESC
"""

In [27]:
run_query(query5, description="Department-wise Student Count and Average Scores")

=======================================================
DEPARTMENT-WISE STUDENT COUNT AND AVERAGE SCORES
=======================================================
         department  student_count  avg_math_score  avg_science  \
0  Computer Science             13           85.62        84.46
1        Mechanical              6           71.00        76.50
2       Electronics              6           71.00        74.17
3             Civil              5           63.40        66.60

   avg_programming
0            89.23
1            49.33
2            61.50
3            40.60

,department,student_count,avg_math_score,avg_science,avg_programming
0,Computer Science,13,85.62,84.46,89.23
1,Mechanical,6,71.00,76.50,49.33
2,Electronics,6,71.00,74.17,61.50
3,Civil,5,63.40,66.60,40.60

In [28]:
query6 ="""
 SELECT
  department,
  ROUND(AVG(math_score),2) AS avg_math_score,
  COUNT(*) AS students,
FROM STUDENTS
GROUP BY department
ORDER BY avg_math_score DESC
"""

In [31]:
query6 ="""
 SELECT
  department,
  ROUND(AVG(math_score),2) AS avg_math_score,
  COUNT(*) AS students
FROM STUDENTS
GROUP BY department
ORDER BY avg_math_score DESC
"""
run_query(query6, description="Department-wise Student Count and Average Scores")

=======================================================
DEPARTMENT-WISE STUDENT COUNT AND AVERAGE SCORES
=======================================================
         department  avg_math_score  students
0  Computer Science           85.62        13
1        Mechanical           71.00         6
2       Electronics           71.00         6
3             Civil           63.40         5

         department  avg_math_score  students
0  Computer Science           85.62        13
1        Mechanical           71.00         6
2       Electronics           71.00         6
3             Civil           63.40         5

In [32]:
query7 ="""
 SELECT
  gender,
  COUNT(*) AS new_students,
  ROUND(AVG(math_score),2) AS avg_math_score,
  ROUND(AVG(science_score),2)AS avg_science,
  ROUND(AVG(programming_score),2) AS avg_programming
FROM STUDENTS
GROUP BY department
ORDER BY gender
"""

In [33]:
result7=run_query(query7, description="Gender-wise Student Count and Average Scores")

=======================================================
GENDER-WISE STUDENT COUNT AND AVERAGE SCORES
=======================================================
   gender  new_students  avg_math_score  avg_science  avg_programming
0  Female             6           71.00        76.50            49.33
1    Male             5           63.40        66.60            40.60
2    Male            13           85.62        84.46            89.23
3    Male             6           71.00        74.17            61.50

In [34]:
query8 ="""
 SELECT
  name,
  department,
  math_score,science_score,english_score, programming_score AS
  total_score, attendance_percentage
FROM STUDENTS
GROUP BY department
ORDER BY avg_math_score DESC
"""

In [8]:
import pandas as pd
import sqlite3

# Ensure df is defined for this cell's operations, using the full path to the file
df = pd.read_csv('/content/student_performance.csv')

# Establish a connection for this cell's operations
conn_local = sqlite3.connect(':memory:')

# Load the main DataFrame 'df' into the 'students' table in this connection
df.to_sql('students', conn_local, if_exists='replace', index=False)

# Define query5 (assuming it's the intended query for department data)
query5 ="""
 SELECT
  department,
  COUNT(*) AS student_count,
  ROUND(AVG(math_score),2) AS avg_math_score,
  ROUND(AVG(science_score),2)AS avg_science,
  ROUND(AVG(programming_score),2) AS avg_programming
FROM STUDENTS
GROUP BY department
ORDER BY avg_math_score DESC
"""

# Get the department data using pd.read_sql_query against the local connection
# This directly creates the DataFrame 'dept_df'
dept_df = pd.read_sql_query(query5, conn_local)

# Now, save this dept_df to a new table 'departments' in the same local connection
dept_df.to_sql('departments', conn_local, if_exists='replace', index=False)

print("Created 'departments' table:")
print(dept_df.to_string(index=False))

# Close the local connection
conn_local.close()

Created 'departments' table:
      department  student_count  avg_math_score  avg_science  avg_programming
Computer Science             13           85.62        84.46            89.23
      Mechanical              6           71.00        76.50            49.33
     Electronics              6           71.00        74.17            61.50
           Civil              5           63.40        66.60            40.60

In [ ]:
dept_df=pd.DataFrame(dept_df)
deptdf_tos